version: "2"
services:
  web:
    command: [ "npm", "run", "dev" ]
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./templates:/usr/src/app/templates
  mongo:
    image: mongo
    ports:
    - "27017:27017"